spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        input-in-0:
          destination: kafka-output
          group: exampleOfConsumerGroup
        output:
          destination: kafka-output
      default:
        contentType: application/json
      source: input
management:
  endpoints:
    enabled-by-default:
