spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        input-in-0:
          destination: kafka-output
          group: exampleOfConsumerGroup
        output:
          destination: kafka-output
      default:
        contentType: application/json
      source: input
management:
  endpoints:
    enabled-by-default:

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
      auto: false
      use-default-aws-region-chain: true
    credentials:
      access-key: AKIAVCTGKVB4HLAI35FW
      secret-key: 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