spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        input-in-0:
          destination: kafka-output
          group: exampleOfConsumerGroup
        output:
          destination: kafka-output
      source: input

cloud:
  aws:
    stack:
      auto: false
      ##This property must be true when run app on AWS
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIAVCTGKVB4HLAI35FW
      secret-key: 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

sqs:
  queue: HCLSQSQueue